# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2

updates:
  # Maintain dependencies for Github Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # Maintain Dockerfile dependencies
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
